_target_: evaluation.dataset.voc.VOCDataset
root: "/your root/seg/" 
split: "train"              
year: "2012"
download: false             
include_labels: true
num_classes: 21             
tag: "voc" 